module Inline.View exposing (inlines, suite)

{-| Exact markup of `Lia.Markdown.Inline.View` for every `Inline` and
`Reference` constructor, recorded from the implementation before the
refactoring (see `Inline.ViewSnapshots`, which is generated by running these
tests against the old code).

If the markup is changed on purpose, re-record the snapshots.

-}

import Array
import Dict exposing (Dict)
import Expect
import Html exposing (Html)
import Html.Attributes
import HtmlSnapshot
import I18n.Translations exposing (Lang(..))
import Inline.ViewSnapshots exposing (snapshots)
import Lia.Markdown.Effect.Script.Types exposing (Msg)
import Lia.Markdown.HTML.Types exposing (Node(..))
import Lia.Markdown.Inline.Config as Config exposing (Config)
import Lia.Markdown.Inline.Types exposing (Inline(..), Reference(..))
import Lia.Markdown.Inline.View as View
import Lia.Markdown.Quiz.Block.Types exposing (State(..))
import Lia.Settings.Types exposing (Mode(..))
import Test exposing (Test, describe, test)


config : Config ()
config =
    Config.init
        { mode = Textbook
        , visible = Nothing
        , slide = 0
        , speaking = Nothing
        , paused = Nothing
        , lang = En
        , theme = Nothing
        , light = True
        , tooltips = False
        , hideVideoComments = False
        , media = Dict.empty
        , scripts = Array.empty
        , translations = Nothing
        , formulas = Nothing
        , sync = Nothing
        }


{-| Presentation mode with slide 1 visible: no lazy loading, effects hidden.
-}
presentation : Config ()
presentation =
    Config.init
        { mode = Presentation
        , visible = Just 1
        , slide = 0
        , speaking = Nothing
        , paused = Nothing
        , lang = De
        , theme = Nothing
        , light = False
        , tooltips = True
        , hideVideoComments = False
        , media = Dict.fromList [ ( "img.png", ( 320, 200 ) ) ]
        , scripts = Array.empty
        , translations = Just { old = "en", new = "fr", name = Nothing }
        , formulas = Just (Dict.fromList [ ( "\\RR", "\\mathbb{R}" ) ])
        , sync = Nothing
        }


{-| Quiz inputs `0 ..` in the given states, options for every input.
-}
withInput : Bool -> List State -> List Bool -> Config () -> Config ()
withInput active states partial c =
    { c
        | input =
            { state = Array.fromList states
            , options =
                Array.fromList
                    (List.map
                        (\_ -> [ [ Chars "opt0" [] ], [ Bold (Chars "opt1" []) [] ], [ Chars "opt2" [] ] ])
                        states
                    )
            , randomize = Nothing
            , on = \cmd id value -> "on(" ++ cmd ++ "," ++ String.fromInt id ++ "," ++ value ++ ")"
            , path = []
            , active = active
            , partiallyCorrect = Array.fromList partial
            }
    }


attr : List ( String, String )
attr =
    [ ( "class", "x" ), ( "style", "color:red" ) ]


chars : String -> Inline
chars s =
    Chars s []


inlines : List ( String, Inline )
inlines =
    [ ( "chars", chars "plain" )
    , ( "chars with attr", Chars "plain" attr )
    , ( "bold", Bold (chars "b") [] )
    , ( "bold attr", Bold (chars "b") attr )
    , ( "bold nested", Bold (Italic (chars "bi") []) attr )
    , ( "italic", Italic (chars "i") attr )
    , ( "strike", Strike (chars "s") attr )
    , ( "underline", Underline (chars "u") attr )
    , ( "superscript", Superscript (chars "sup") attr )
    , ( "superscript nested", Superscript (Container [ chars "a", Bold (chars "b") [] ] []) [] )
    , ( "verbatim", Verbatim "code" [] )
    , ( "verbatim attr", Verbatim "code" attr )
    , ( "formula inline", Formula "false" "a^2" [] )
    , ( "formula block", Formula "true" "\\RR" [] )
    , ( "formula attr", Formula "false" "x" attr )
    , ( "symbol", Symbol "→" [] )
    , ( "symbol attr", Symbol "→" attr )
    , ( "footnote", FootnoteMark "1" [] )
    , ( "footnote attr", FootnoteMark "note" attr )
    , ( "container", Container [ chars "a", Italic (chars "b") [], chars "c" ] attr )
    , ( "container empty", Container [] [] )
    , ( "html node", IHTML (Node "span" [ ( "id", "n" ) ] [ chars "in", Bold (chars "b") [] ]) [] )
    , ( "html node attr", IHTML (Node "kbd" [] [ chars "k" ]) attr )
    , ( "html inner", IHTML (InnerHtml "<br>") [] )
    , ( "effect", EInline { content = [ chars "e", Bold (chars "f") [] ], playback = False, begin = 1, end = Nothing, voice = "", id = 0 } attr )
    , ( "effect range", EInline { content = [ chars "e" ], playback = True, begin = 2, end = Just 4, voice = "Deutsch Female", id = 3 } [] )
    , ( "script missing", Script 0 [] )
    , ( "link", Ref (Link [ chars "alt" ] "https://a.org" Nothing) [] )
    , ( "link title attr", Ref (Link [ Bold (chars "alt") [] ] "https://a.org" (Just [ chars "ti", Italic (chars "tle") [] ])) attr )
    , ( "link blank title", Ref (Link [ chars "alt" ] "https://a.org" (Just [ chars "  " ])) [] )
    , ( "link anchor", Ref (Link [ chars "sec" ] "#3" Nothing) [] )
    , ( "mail", Ref (Mail [ chars "me" ] "mailto:a@b.de" (Just [ chars "t" ])) [] )
    , ( "image", Ref (Image [ chars "alt" ] "img.png" Nothing) [] )
    , ( "image no alt", Ref (Image [] "other.png" Nothing) [] )
    , ( "image title attr", Ref (Image [ chars "alt" ] "other.png" (Just [ chars "cap" ])) attr )
    , ( "audio", Ref (Audio [ chars "a" ] ( False, "a.mp3" ) (Just [ chars "t" ])) attr )
    , ( "audio tube", Ref (Audio [ chars "a" ] ( True, "https://deezer/x" ) Nothing) attr )
    , ( "movie", Ref (Movie [ chars "m" ] ( False, "m.mp4" ) (Just [ chars "t" ])) attr )
    , ( "movie tube youtube", Ref (Movie [ chars "m" ] ( True, "https://www.youtube-nocookie.com/embed/abc" ) Nothing) [] )
    , ( "movie tube youtube query", Ref (Movie [ chars "m" ] ( True, "https://www.youtube-nocookie.com/embed/abc?start=3" ) (Just [ chars "t" ])) attr )
    , ( "movie tube other", Ref (Movie [ chars "m" ] ( True, "https://player.vimeo.com/video/1" ) Nothing) [] )
    , ( "embed", Ref (Embed [ chars "e" ] "https://e.org/x" Nothing) [] )
    , ( "embed title attr", Ref (Embed [ chars "e" ] "https://e.org/x" (Just [ chars "cap" ])) attr )
    , ( "preview lia", Ref (Preview_Lia "https://c.org/README.md") attr )
    , ( "preview link", Ref (Preview_Link "https://c.org") [] )
    , ( "qr", Ref (QR_Link "https://q.org" Nothing) [] )
    , ( "qr title attr", Ref (QR_Link "https://q.org" (Just [ chars "scan" ])) attr )
    ]


{-| Quiz inputs, rendered with input 0 in the given state.
-}
quizzes : List ( String, Config (), Inline )
quizzes =
    let
        quiz =
            Quiz ( "5rem", 0 ) attr
    in
    [ ( "text active", withInput True [ Text "abc" ] [] config, quiz )
    , ( "text inactive", withInput False [ Text "abc" ] [] config, quiz )
    , ( "text correct", withInput True [ Text "abc" ] [ True ] config, quiz )
    , ( "text wrong", withInput True [ Text "abc" ] [ False ] config, quiz )
    , ( "text resolved hides highlight", withInput False [ Text "abc" ] [ False ] config, quiz )
    , ( "select closed", withInput True [ Select False [ 1 ] ] [] config, quiz )
    , ( "select open", withInput True [ Select True [ -1 ] ] [] config, quiz )
    , ( "select out of range", withInput True [ Select False [ 7 ] ] [ True ] config, quiz )
    , ( "select inactive", withInput False [ Select True [ 0 ] ] [] config, quiz )
    , ( "select randomized"
      , let
            c =
                withInput True [ Select True [ 0 ] ] [] config

            input =
                c.input
        in
        { c | input = { input | randomize = Just (Array.fromList [ [ 2, 0, 1 ] ]) } }
      , quiz
      )
    , ( "select multiple", withInput True [ Select False [ 0, 1 ] ] [] config, quiz )
    , ( "drop single", withInput True [ Drop False False [ 1 ] ] [] config, quiz )
    , ( "drop single empty", withInput True [ Drop False False [ 9 ] ] [ True ] config, quiz )
    , ( "drop single wrong", withInput True [ Drop False False [ 0 ] ] [ False ] config, quiz )
    , ( "drop empty", withInput True [ Drop False False [] ] [] config, quiz )
    , ( "drop pair", withInput True [ Drop True False [ 0, 2 ] ] [ True ] config, quiz )
    , ( "drop pair wrong", withInput True [ Drop False True [ 0, 1 ] ] [ False ] config, quiz )
    , ( "missing state", withInput True [] [] config, quiz )
    ]


expectSnapshot : String -> Html (Msg ()) -> Expect.Expectation
expectSnapshot name html =
    case Dict.get name snapshots of
        Just recorded ->
            HtmlSnapshot.expect recorded html

        Nothing ->
            Expect.fail ("RECORD:" ++ HtmlSnapshot.toString html)


snapshot : String -> Html (Msg ()) -> Test
snapshot name html =
    test name <| \_ -> expectSnapshot name html


wrap : List (Html (Msg ())) -> Html (Msg ())
wrap =
    Html.div []


drops : Config ()
drops =
    withInput True
        [ Drop False True [ 1 ]
        , Text "x"
        , Drop False False [ 0, 2 ]
        , Drop True False []
        ]
        []
        config


suite : Test
suite =
    describe "Lia.Markdown.Inline.View snapshots"
        [ inlines
            |> List.map (\( name, inline ) -> snapshot ("view " ++ name) (View.view config inline))
            |> describe "view"
        , inlines
            |> List.map (\( name, inline ) -> snapshot ("presentation " ++ name) (View.view presentation inline))
            |> describe "view in presentation"
        , quizzes
            |> List.map (\( name, c, inline ) -> snapshot ("quiz " ++ name) (View.view c inline))
            |> describe "quiz"
        , inlines
            |> List.map (\( name, inline ) -> snapshot ("reduce " ++ name) (wrap (View.reduce config [ chars "a. b", inline ])))
            |> describe "reduce"
        , snapshot "reduce all" (wrap (View.reduce config (List.map Tuple.second inlines)))
        , snapshot "viewer" (wrap (View.viewer config (List.map Tuple.second inlines)))
        , inlines
            |> List.map (\( name, inline ) -> snapshot ("media " ++ name) (View.viewMedia presentation inline))
            |> describe "viewMedia"
        , snapshot "media image config" (View.viewMedia config (Ref (Image [ chars "alt" ] "img.png" (Just [ chars "t" ])) attr))
        , snapshot "media oembed"
            (View.viewMedia { config | oEmbed = Just { maxwidth = 300, maxheight = 0, scale = 0.5, thumbnail = True } }
                (Ref (Embed [ chars "e" ] "https://e.org/x" Nothing) attr)
            )
        , snapshot "media oembed height"
            (View.viewMedia { config | oEmbed = Just { maxwidth = 0, maxheight = 200, scale = 1, thumbnail = False } }
                (Ref (Embed [ chars "e" ] "https://e.org/x" Nothing) [])
            )
        , snapshot "image no zoom" (View.view { config | image_zoom = False } (Ref (Image [ chars "alt" ] "img.png" Nothing) []))
        , snapshot "quiz drops" (wrap (View.viewQuizDrops drops))
        , snapshot "quiz drops inactive" (wrap (View.viewQuizDrops { drops | input = (\i -> { i | active = False }) drops.input }))
        , snapshot "drop here" (View.dropHere [ Html.Attributes.class "x" ] |> Html.map never)
        , snapshot "audio" (View.audio [] { url = "a.mp3", controls = False, preload = "auto", errorHandling = False } |> Html.map never)
        , snapshot "audio error" (View.audio [] { url = "a.mp3", controls = True, preload = "none", errorHandling = True } |> Html.map never)
        , snapshot "view_inf" (View.view_inf Array.empty En True False Nothing Nothing Nothing (Ref (Image [ chars "alt" ] "img.png" Nothing) []))
        , snapshot "view_inf media" (View.view_inf Array.empty De False True Nothing (Just Dict.empty) (Just (Dict.fromList [ ( "img.png", ( 1, 2 ) ) ])) (Container [ Ref (Image [] "img.png" Nothing) [], Ref (Link [ chars "l" ] "https://l.org" Nothing) [] ] []))
        ]
