name: Deploy LiaScript-Web-Site to Pages

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  liascript:
    runs-on: ubuntu-latest
    steps:
      - name: Set ELM_HOME
        run: echo "ELM_HOME=${GITHUB_WORKSPACE}/.elm" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # build LiaScript
      - name: LiaScript - download
        run: git clone --branch development https://github.com/LiaScript/LiaScript.git
      - name: LiaScript - prebuild
        run: |
          cd LiaScript
          npm install --allow-git=all
          npm run prebuild
      - name: LiaScript - patches
        run: |
          cd LiaScript
          git submodule update --init --recursive
          cd patches
          make
          cd ..
          rm -rf elm-stuff .parcel-cache

      - name: LiaScript - build (PWA)
        env:
          WEBSOCKET_SERVER: ${{ secrets.WEBSOCKET_SERVER }}
          WEBRTC_SIGNALING_SERVERS: ${{ secrets.WEBRTC_SIGNALING_SERVERS }}
          WEBRTC_ICE_SERVERS: ${{ secrets.WEBRTC_ICE_SERVERS }}
          ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
          PUBNUB_PUBLISH_KEY: ${{ secrets.PUBNUB_PUBLISH_KEY }}
          PUBNUB_SUBSCRIBE_KEY: ${{ secrets.PUBNUB_SUBSCRIBE_KEY }}
        run: |
          cd LiaScript
          make all2

      - name: Create ZIP artifact (PWA)
        run: |
          zip -r pwa-build.zip LiaScript/dist/*

      - name: LiaScript - build (OPAL)
        run: |
          cd LiaScript
          npm run build:opal

      - name: Create ZIP artifact (OPAL)
        run: |
          zip -r opal-build.zip LiaScript/dist/*

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" pwa-build.zip opal-build.zip \
            --title "Release for ${{ github.ref }}" --notes ""
